### ISSUE TITLE
sizes

### ISSUE THREAD

**Issue by PetRockMiner** [missionfloyd/webui-qrcode-generator#4]
can you add some way to know what the scale sizes are, or an option to make it 512x512 or 768x768 and also still adjust the border?

**Comment by missionfloyd** [comment]
Scale is how many pixels each square is, so the size depends on how big the QR code ends up being.

I added separate "Scale to" and "Scale by" modes, like img2img and extras have.
![image](https://github.com/missionfloyd/webui-qrcode-generator/assets/4073789/ffd2024d-7438-4d2b-b0f2-3c1c020647d8)

**Comment by PetRockMiner** [comment]
AWESOME! TYVM!
